name: Joseph Turk
description: Joseph Turk is a web developer, musician, and project manager who lives in Madison, WI.

url: "http://localhost:4000"

exclude: [scss]

gems: [jekyll-paginate]

paginate: 5
paginate_path: "blog/page:num/"

markdown: kramdown
permalink: pretty
highlighter: rouge

collections:
  portfolio:
    output: true

sass:
  sass_dir: _scss
  style: :compressed
